// @ts-nocheck
import { Router } from "express";
import crypto from "crypto";
import { z } from "zod";
import { AppError } from "../middleware/errorHandler";
import { generateToken, requireCustomerAuth } from "../middleware/auth";
import { readDb, writeDb, compareSecret, hashSecret, createId, nowIso } from "../lib/db";
const router = Router();
const registerSchema = z.object({ fullName: z.string().min(2).max(120), email: z.string().email(), phone: z.string().optional(), password: z.string().min(6) });
const loginSchema = z.object({ email: z.string().email(), password: z.string().min(6) });
const profileSchema = z.object({ fullName: z.string().min(2).max(120), phone: z.string().optional().nullable() });
const changePasswordSchema = z.object({ currentPassword: z.string().min(6), newPassword: z.string().min(6) });
const forgotPasswordSchema = z.object({ email: z.string().email() });
const resetPasswordSchema = z.object({ token: z.string().min(20), newPassword: z.string().min(6) });
function formatUser(user) { return { id: user.id, fullName: user.fullName, email: user.email, phone: user.phone, role: "customer", createdAt: user.createdAt }; }
router.post("/register", async (req, res, next) => { try { const data = registerSchema.parse(req.body); const db = await readDb(); const email = String(data.email).toLowerCase(); const existing = db.customerUsers.find((item) => String(item.email).toLowerCase() === email); if (existing) throw new AppError(409, "An account with that email already exists"); const now = nowIso(); const user = { id: createId(), fullName: data.fullName, email, phone: data.phone || null, passwordHash: await hashSecret(data.password), isActive: true, createdAt: now, updatedAt: now }; db.customerUsers.push(user); await writeDb(db); const token = generateToken({ id: user.id, email: user.email, role: "customer", accountType: "customer" }); res.status(201).json({ token, user: formatUser(user) }); } catch (e) { next(e); } });
router.post("/login", async (req, res, next) => { try { const data = loginSchema.parse(req.body); const db = await readDb(); const user = db.customerUsers.find((item) => String(item.email).toLowerCase() === String(data.email).toLowerCase()); if (!user || user.isActive === false) throw new AppError(401, "Invalid credentials"); const valid = await compareSecret(user.passwordHash, data.password); if (!valid) throw new AppError(401, "Invalid credentials"); const token = generateToken({ id: user.id, email: user.email, role: "customer", accountType: "customer" }); res.json({ token, user: formatUser(user) }); } catch (e) { next(e); } });
router.get("/me", requireCustomerAuth, async (req, res, next) => { try { const db = await readDb(); const user = db.customerUsers.find((item) => item.id === req.customerUser.id); if (!user) throw new AppError(404, "Customer not found"); res.json(formatUser(user)); } catch (e) { next(e); } });
router.put("/profile", requireCustomerAuth, async (req, res, next) => { try { const data = profileSchema.parse(req.body); const db = await readDb(); const user = db.customerUsers.find((item) => item.id === req.customerUser.id); if (!user) throw new AppError(404, "Customer not found"); user.fullName = data.fullName; user.phone = data.phone || null; user.updatedAt = nowIso(); await writeDb(db); res.json(formatUser(user)); } catch (e) { next(e); } });
router.post("/change-password", requireCustomerAuth, async (req, res, next) => { try { const data = changePasswordSchema.parse(req.body); if (data.currentPassword === data.newPassword) throw new AppError(400, "New password must be different from the current password"); const db = await readDb(); const user = db.customerUsers.find((item) => item.id === req.customerUser.id); if (!user) throw new AppError(404, "Customer not found"); const valid = await compareSecret(user.passwordHash, data.currentPassword); if (!valid) throw new AppError(400, "Current password is incorrect"); user.passwordHash = await hashSecret(data.newPassword); user.updatedAt = nowIso(); db.passwordResetTokens.forEach((item) => { if (item.customerId === user.id && !item.usedAt) item.usedAt = nowIso(); }); await writeDb(db); res.json({ message: "Password updated successfully" }); } catch (e) { next(e); } });
router.post("/forgot-password", async (req, res, next) => { try { const data = forgotPasswordSchema.parse(req.body); const db = await readDb(); const user = db.customerUsers.find((item) => String(item.email).toLowerCase() === String(data.email).toLowerCase()); if (!user || user.isActive === false) return res.json({ message: "If an account with that email exists, a reset link has been generated." }); db.passwordResetTokens.forEach((item) => { if (item.customerId === user.id && !item.usedAt) item.usedAt = nowIso(); }); const token = crypto.randomBytes(32).toString("hex"); db.passwordResetTokens.push({ id: createId(), customerId: user.id, token, expiresAt: new Date(Date.now() + 3600_000).toISOString(), usedAt: null, createdAt: nowIso() }); await writeDb(db); const response = { message: "If an account with that email exists, a reset link has been generated." }; if (process.env.NODE_ENV !== "production") { response.resetToken = token; response.resetUrl = `/reset-password?token=${token}`; } res.json(response); } catch (e) { next(e); } });
router.post("/reset-password", async (req, res, next) => { try { const data = resetPasswordSchema.parse(req.body); const db = await readDb(); const resetToken = db.passwordResetTokens.find((item) => item.token === data.token); if (!resetToken || resetToken.usedAt || new Date(resetToken.expiresAt) < new Date()) throw new AppError(400, "This password reset link is invalid or has expired"); const user = db.customerUsers.find((item) => item.id === resetToken.customerId); if (!user) throw new AppError(404, "Customer not found"); user.passwordHash = await hashSecret(data.newPassword); user.updatedAt = nowIso(); resetToken.usedAt = nowIso(); db.passwordResetTokens.forEach((item) => { if (item.customerId === resetToken.customerId && item.id !== resetToken.id && !item.usedAt) item.usedAt = nowIso(); }); await writeDb(db); res.json({ message: "Password reset successfully" }); } catch (e) { next(e); } });
export default router;
